import test from 'node:test'
import assert from 'node:assert/strict'
import { parseAmount,summarize,validateBackup,emptyFinance,validDate } from '../src/financeModel.ts'
import { planAssistant,parseDate } from '../src/assistantPlan.ts'
const now=new Date(2026,8,20,12,0),data={tasks:[],contacts:[],events:[],reminders:[],sales:[],nexus:[]}
test('dinheiro usa centavos sem perda e aceita formato brasileiro',()=>{assert.equal(parseAmount('1.234,56'),123456);assert.equal(parseAmount('0,01'),1);assert.equal(parseAmount('12,3'),1230)})
test('recusa valores negativos, notação científica e centavos inválidos',()=>{for(const value of ['-1','0','1e4','1,001','NaN','Infinity','1.23.45'])assert.throws(()=>parseAmount(value))})
test('saldo realizado separa pendências e mantém período',()=>{const rows=[{id:'1',description:'Renda',kind:'income',amount:10000,status:'paid',date:'2026-09-20',category:'Salário',notes:''},{id:'2',description:'Conta',kind:'expense',amount:2500,status:'paid',date:'2026-09-20',category:'Outros',notes:''},{id:'3',description:'Pendente',kind:'expense',amount:3000,status:'pending',date:'2026-09-22',category:'Outros',notes:''},{id:'4',description:'Outro mês',kind:'income',amount:99999,status:'paid',date:'2026-08-20',category:'Outros',notes:''}] as any;assert.deepEqual(summarize(rows,'2026-09'),{income:10000,expense:2500,payable:3000,receivable:0,balance:7500,projected:4500})})
test('backup recusa registros inválidos, datas impossíveis e ids duplicados',()=>{assert.equal(validDate('2026-02-30'),false);const e={id:'1',description:'Conta',kind:'expense',category:'Outros',amount:1000,status:'pending',date:'2026-09-20',notes:''};assert.throws(()=>validateBackup({...emptyFinance(),entries:[e,e]}));assert.throws(()=>validateBackup({...emptyFinance(),entries:[{...e,amount:1.5}]}));assert.equal(validateBackup({...emptyFinance(),entries:[e]}).entries.length,1)})
test('datas em português aceitam acento, horário e dia seguinte',()=>{const d=parseDate('amanhã às 9',now)!;assert.equal(new Date(d.iso).getDate(),21);assert.equal(new Date(d.iso).getHours(),9);assert.equal(parseDate('hoje às 29h',now),null)})
test('assistente prepara criação sem executar ou alterar os dados',()=>{const snapshot=JSON.stringify(data);const plan=planAssistant('tarefa ligar para João amanhã às 9',data,now);assert.equal(plan.kind,'action');if(plan.kind==='action'){assert.equal(plan.table,'tasks');assert.equal(plan.values.title,'ligar para João');assert.equal(new Date(String(plan.values.due_at)).getDate(),21)}assert.equal(JSON.stringify(data),snapshot)})
test('assistente não escolhe entre nomes ambíguos',()=>{const plan=planAssistant('concluir tarefa ligar',{...data,tasks:[{id:'1',title:'ligar João'},{id:'2',title:'ligar Maria'}]},now);assert.equal(plan.kind,'clarify')})
test('retornos incluem contatos pessoais e clientes Nexus',()=>{const plan=planAssistant('Quais clientes preciso chamar hoje?',{...data,contacts:[{name:'João',next_contact_at:new Date(2026,8,19).toISOString()}],nexus:[{kind:'clients',title:'Loja Maria'}]},now);assert.equal(plan.kind,'answer');if(plan.kind==='answer')assert.match(plan.text,/João.*Loja Maria/)})
test('comando desconhecido vira proposta de captura, nunca salvamento automático',()=>{const plan=planAssistant('uma ideia qualquer',data,now);assert.equal(plan.kind,'action');if(plan.kind==='action')assert.equal(plan.table,'inbox')})
test('ação sem data pede esclarecimento',()=>{assert.equal(planAssistant('me lembre de ligar para João',data,now).kind,'clarify')})
test('valores da venda reconhecem centavos com vírgula e ponto',()=>{for(const [input,amount] of [['venda 350,50 para Maria',350.5],['venda 350.50 para Maria',350.5],['venda 1.250,50 para Maria',1250.5]] as const){const p=planAssistant(input,data,now);assert.equal(p.kind,'action');if(p.kind==='action')assert.equal(p.values.amount,amount)}})
test('reconhece dias da semana na agenda',()=>{const d=parseDate('segunda às 14h',now)!;assert.equal(new Date(d.iso).getDay(),1);assert.equal(new Date(d.iso).getHours(),14)})
