import { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react'
import { CalendarDays, CheckCircle2, CircleDollarSign, Inbox, LayoutDashboard, ListTodo, LogOut, Plus, Sparkles, Bell, Trash2, NotebookPen, Users, Target, History, Menu, X, ArrowUpRight, Search, Layers3, Wallet, CloudCog } from 'lucide-react'
import { supabase } from './lib/supabase'
import './App.css'
const NexusPanel=lazy(()=>import('./NexusPanel').then(m=>({default:m.NexusPanel})))
import { useEditor } from './Editor'
import { hub, getWorkspace, iso, localInput } from './hub'
import type { Source, LinkedTask, PendingItem } from './hub'
import { PendingCenter } from './PendingCenter'
const ClientPage=lazy(()=>import('./ClientPage').then(m=>({default:m.ClientPage})))
import { AppExperience } from './AppExperience'
import { SmartAssistant } from './SmartAssistant'
import { useNexusSales } from './useNexusSales'
import { NexusSales } from './NexusSales'
import { BlingPanel } from './BlingPanel'
import { orderTotal, salesForPeriod } from './nexusSalesModel'
const PersonalFinance=lazy(()=>import('./PersonalFinance').then(m=>({default:m.PersonalFinance})))
type Task={origin?:'nexus';source_kind?:Source['kind'];source_id?:string;updated_at?:string;id:string;title:string;status:'pending'|'done';priority:'low'|'normal'|'high';due_at:string|null;category:string|null;recurrence:string|null}
type Sale={id:string;customer:string|null;description:string;amount:number;sold_at:string;notes:string|null}; type Reminder={id:string;title:string;remind_at:string;done:boolean}; type Event={id:string;title:string;starts_at:string;ends_at:string|null;notes:string|null}; type InboxItem={id:string;content:string;processed:boolean}
type Note={id:string;title:string;content:string;pinned:boolean}; type Contact={id:string;name:string;phone:string|null;company:string|null;next_contact_at:string|null;notes:string|null}; type Goal={id:string;title:string;target:number|null;current:number;period:string}; type Activity={id:string;kind:string;description:string;created_at:string}
type View='bling'|'finance'|'pending'|'client'|'today'|'tasks'|'reminders'|'calendar'|'nexus'|'sales'|'inbox'|'notes'|'contacts'|'goals'|'history'
const menu=[['pending','Pendências',Bell],['today','Visão geral',LayoutDashboard],['tasks','Tarefas',ListTodo],['reminders','Lembretes',Bell],['calendar','Calendário',CalendarDays],['nexus','Nexus',Sparkles],['bling','Bling empresarial',CloudCog],['finance','Financeiro pessoal',Wallet],['sales','Vendas',CircleDollarSign],['inbox','Caixa rápida',Inbox],['notes','Notas',NotebookPen],['contacts','Contatos',Users],['goals','Metas',Target],['history','Histórico',History]] as const
export default function App(){
 const [session,setSession]=useState<any>(null),[view,setView]=useState<View>(()=>new URLSearchParams(location.search).has('bling')?'bling':'today'),[mobileMore,setMobileMore]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('')
 const [personalTasks,setPersonalTasks]=useState<Task[]>([]),[sales,setSales]=useState<Sale[]>([]),[reminders,setReminders]=useState<Reminder[]>([]),[events,setEvents]=useState<Event[]>([]),[inbox,setInbox]=useState<InboxItem[]>([]),[notes,setNotes]=useState<Note[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[goals,setGoals]=useState<Goal[]>([]),[history,setHistory]=useState<Activity[]>([])
 const editor=useEditor()
 const nexusSales=useNexusSales(session?.user.id)
 const [linkedTasks,setLinkedTasks]=useState<LinkedTask[]>([]),[hubPending,setHubPending]=useState<PendingItem[]>([]),[hubError,setHubError]=useState(''),[hubBusy,setHubBusy]=useState(false),[hubMore,setHubMore]=useState(false),[lastRead,setLastRead]=useState(''),[clientId,setClientId]=useState(''),[nexusTarget,setNexusTarget]=useState<Source|null>(null)
 const tasks:Task[]=[...personalTasks,...linkedTasks]
 const loadVersion=useRef(0),hubVersion=useRef(0)
 function openSource(source:Source){if(source.kind==='clients'){setClientId(source.id);setView('client')}else{setNexusTarget(source);setView('nexus')}}
 async function refreshHub(){const version=++hubVersion.current;setHubBusy(true);setHubError('');try{const [all,pending]=await Promise.all([getWorkspace(),hub('overview')]);if(version!==hubVersion.current)return;setLinkedTasks(all);setHubPending(pending.items);setHubMore(pending.hasMore)}catch(e){if(version===hubVersion.current)setHubError(e instanceof Error?e.message:'Não foi possível atualizar o Nexus.')}finally{if(version===hubVersion.current)setHubBusy(false)}}
 function createLinked(source:Source){const id=crypto.randomUUID();editor.open({title:'Criar tarefa vinculada',description:'A tarefa ficará ligada ao registro de origem no Nexus.',fields:[{name:'title',label:'O que precisa ser feito?',required:true,value:source.kind==='orders'?'Acompanhar pedido '+(source.title||''):source.kind==='clients'?'Retornar ao cliente '+(source.title||''):'Acompanhar interesse '+(source.title||'')},{name:'due_at',label:'Prazo',type:'datetime-local'},{name:'priority',label:'Prioridade',value:'normal',options:[['low','Baixa'],['normal','Normal'],['high','Alta']]}],submitLabel:'Criar tarefa',save:async v=>{const r=await hub('save_followup',{id,source_kind:source.kind,source_id:source.id,title:v.title,priority:v.priority,status:'pending',due_at:iso(v.due_at)});setLinkedTasks(prev=>[r.task,...prev.filter(t=>t.id!==r.task.id)])}})}
 async function saveLinked(t:Task,patch:Record<string,unknown>){const r=await hub('save_followup',{id:t.id,expected:t.updated_at,title:t.title,priority:t.priority,status:t.status,due_at:t.due_at,...patch});setLinkedTasks(prev=>prev.map(x=>x.id===t.id?r.task:x))}
 async function persist(table:string,id:string,patch:Record<string,unknown>){if(!navigator.onLine)throw new Error('Reconecte antes de salvar.');const {error:failure}=await supabase.from(table).update(patch).eq('id',id).eq('user_id',session.user.id).select('id').single();if(failure)throw new Error('Não foi possível salvar. Seus campos foram preservados; tente novamente.');await load()}
 const notifiedReminders=useRef(new Set<string>())
 const [globalSearch,setGlobalSearch]=useState('')
 const [newTask,setNewTask]=useState(''),[taskPriority,setTaskPriority]=useState<'low'|'normal'|'high'>('normal'),[taskDue,setTaskDue]=useState(''),[taskCategory,setTaskCategory]=useState(''),[taskRecurrence,setTaskRecurrence]=useState(''),[quick,setQuick]=useState(''),[rt,setRt]=useState(''),[ra,setRa]=useState(''),[et,setEt]=useState(''),[ea,setEa]=useState(''),[ee,setEe]=useState(''),[en,setEn]=useState(''),[sc,setSc]=useState(''),[sd,setSd]=useState(''),[sa,setSa]=useState(''),[saleNotes,setSaleNotes]=useState(''),[saleSearch,setSaleSearch]=useState(''),[salePeriod,setSalePeriod]=useState<'all'|'today'|'month'>('month'),[nt,setNt]=useState(''),[nc,setNc]=useState(''),[cn,setCn]=useState(''),[cp,setCp]=useState(''),[cc,setCc]=useState(''),[cnext,setCnext]=useState(''),[cnotes,setCnotes]=useState(''),[gt,setGt]=useState(''),[gv,setGv]=useState(''),[goalPeriod,setGoalPeriod]=useState('monthly'),[contactSearch,setContactSearch]=useState(''),[dayBrief,setDayBrief]=useState(''),[briefBusy,setBriefBusy]=useState(false)
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setBusy(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[])
 useEffect(()=>{loadVersion.current++;hubVersion.current++;setPersonalTasks([]);setSales([]);setReminders([]);setEvents([]);setInbox([]);setNotes([]);setContacts([]);setGoals([]);setHistory([]);setLinkedTasks([]);setHubPending([]);setLastRead('');if(session){void load();void refreshHub()}return()=>{loadVersion.current++;hubVersion.current++}},[session?.user.id])
 useEffect(()=>{if(!session)return;const check=()=>{if(document.visibilityState!=='visible')return;const due=reminders.filter(r=>!r.done&&new Date(r.remind_at).getTime()<=Date.now()&&new Date(r.remind_at).getTime()>Date.now()-120000&&!notifiedReminders.current.has(r.id));if(due.length&&'Notification'in window&&Notification.permission==='granted')due.forEach(r=>{notifiedReminders.current.add(r.id);new Notification('ArtOrganiz',{body:r.title})})};check();const timer=setInterval(check,30000);return()=>clearInterval(timer)},[session,reminders])
 async function load(){const version=++loadVersion.current;setBusy(true);setError('');try{const q=await Promise.all([supabase.from('tasks').select('*').order('created_at',{ascending:false}),supabase.from('sales').select('*').order('sold_at',{ascending:false}),supabase.from('reminders').select('*').order('remind_at'),supabase.from('calendar_events').select('*').order('starts_at'),supabase.from('inbox').select('*').order('created_at',{ascending:false}),supabase.from('notes').select('*').order('created_at',{ascending:false}),supabase.from('contacts').select('*').order('created_at',{ascending:false}),supabase.from('goals').select('*').order('created_at',{ascending:false}),supabase.from('activity_feed').select('*').order('created_at',{ascending:false}).limit(50)]);if(version!==loadVersion.current)return;const failed=q.find(x=>x.error);if(failed?.error)throw failed.error;setPersonalTasks(q[0].data||[]);setSales(q[1].data||[]);setReminders(q[2].data||[]);setEvents(q[3].data||[]);setInbox(q[4].data||[]);setNotes(q[5].data||[]);setContacts(q[6].data||[]);setGoals(q[7].data||[]);setHistory(q[8].data||[]);setLastRead(new Date().toISOString())}catch(e){console.error(e);setError('Não foi possível carregar seus dados. Verifique a conexão e tente novamente.')}finally{if(version===loadVersion.current)setBusy(false)}}
 async function generateDayBrief(){setBriefBusy(true);setError('');try{const now=Date.now(),pending=tasks.filter(t=>t.status==='pending'),lateTasks=pending.filter(t=>t.due_at&&new Date(t.due_at).getTime()<now),lateReminders=reminders.filter(r=>!r.done&&new Date(r.remind_at).getTime()<now),todayKey=localDateKey(),todayAgenda=events.filter(e=>localDateKey(new Date(e.starts_at))===todayKey),returns=contacts.filter(c=>c.next_contact_at&&new Date(c.next_contact_at).getTime()<=now);const ranked=pending.slice().sort((a,b)=>((b.priority==='high'?30:0)+(b.due_at&&new Date(b.due_at).getTime()<now?100:0))-((a.priority==='high'?30:0)+(a.due_at&&new Date(a.due_at).getTime()<now?100:0))).slice(0,3);const parts=[];if(lateTasks.length)parts.push(`${lateTasks.length} tarefa${lateTasks.length>1?'s':''} atrasada${lateTasks.length>1?'s':''}`);if(lateReminders.length)parts.push(`${lateReminders.length} lembrete${lateReminders.length>1?'s':''} vencido${lateReminders.length>1?'s':''}`);if(returns.length)parts.push(`${returns.length} retorno${returns.length>1?'s':''} pendente${returns.length>1?'s':''}`);if(todayAgenda.length)parts.push(`${todayAgenda.length} compromisso${todayAgenda.length>1?'s':''} hoje`);const focus=ranked.map(t=>t.title);const summary=parts.length?`Seu foco de hoje: ${parts.join(', ')}.${focus.length?' Priorize: '+focus.join(' → ')+'.':''}`:`Seu dia está sob controle.${focus.length?' Próximas prioridades: '+focus.join(' → ')+'.':' Não há pendências urgentes agora.'}`;setDayBrief(summary);const {error:e}=await supabase.from('daily_briefs').upsert({user_id:session.user.id,brief_date:todayKey,summary,focus_items:focus},{onConflict:'user_id,brief_date'});if(e)throw e;activity('ai','Resumo inteligente do dia atualizado')}catch(e){console.error(e);setError('Não foi possível gerar o resumo inteligente.')}finally{setBriefBusy(false)}}
 async function enableNotifications(){if(!('Notification'in window)){setError('Este dispositivo não oferece notificações do navegador.');return}const permission=await Notification.requestPermission();if(permission==='granted')activity('notification','Notificações ativadas');else setError('Permissão de notificações não foi concedida.')}
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError('E-mail ou senha inválidos.');setBusy(false)}
 async function activity(kind:string,description:string){const {data}=await supabase.from('activity_feed').insert({user_id:session.user.id,kind,description}).select().single();if(data)setHistory(h=>[data,...h].slice(0,50))}
 async function addTask(){if(!newTask.trim())return;setError('');const due=taskDue?new Date(taskDue):null;if(due&&Number.isNaN(due.getTime())){setError('Prazo da tarefa inválido.');return}const {data,error:e}=await supabase.from('tasks').insert({title:newTask.trim(),priority:taskPriority,due_at:due?due.toISOString():null,category:taskCategory.trim()||null,recurrence:taskRecurrence||null,user_id:session.user.id}).select().single();if(e||!data){setError('Não foi possível criar a tarefa.');return}setPersonalTasks(prev=>[data,...prev]);activity('task','Tarefa criada: '+data.title);setNewTask('');setTaskPriority('normal');setTaskDue('');setTaskCategory('');setTaskRecurrence('')}
 async function deleteTask(t:Task){if(!confirm('Excluir esta tarefa?'))return;setError('');if(t.origin==='nexus'){try{await hub('delete_followup',{id:t.id,expected:t.updated_at});setLinkedTasks(prev=>prev.filter(x=>x.id!==t.id))}catch(e){setError(e instanceof Error?e.message:'Falha ao excluir.')}return}const {error:e}=await supabase.from('tasks').delete().eq('id',t.id);if(e){setError('Não foi possível excluir a tarefa.');return}setPersonalTasks(personalTasks.filter(x=>x.id!==t.id));activity('task','Tarefa excluída: '+t.title)}
 async function editTask(t:Task){editor.open({title:'Editar tarefa',fields:[{name:'title',label:'Tarefa',value:t.title,required:true},{name:'priority',label:'Prioridade',value:t.priority,options:[['low','Baixa'],['normal','Normal'],['high','Alta']]},{name:'due_at',label:'Prazo',type:'datetime-local',value:localInput(t.due_at)},...(t.origin==='nexus'?[]:[{name:'category',label:'Categoria',value:t.category},{name:'recurrence',label:'Repetição',value:t.recurrence,options:[['','Sem repetição'],['daily','Diária'],['weekly','Semanal'],['monthly','Mensal']] as [string,string][]}])],save:async v=>{const patch={title:v.title.trim(),priority:v.priority,due_at:iso(v.due_at)};if(!patch.title)throw new Error('Informe o título.');if(t.origin==='nexus')await saveLinked(t,patch);else await persist('tasks',t.id,{...patch,category:v.category.trim()||null,recurrence:v.recurrence||null});void activity('task','Tarefa editada: '+v.title)}})}
 async function toggle(t:Task){if(t.origin==='nexus'){try{await saveLinked(t,{status:t.status==='done'?'pending':'done'})}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.')}return}const done=t.status!=='done';const {error:e}=await supabase.from('tasks').update({status:done?'done':'pending',completed_at:done?new Date().toISOString():null}).eq('id',t.id);if(e){setError('Não foi possível atualizar a tarefa.');return}let next:Task|null=null;if(done&&t.recurrence&&t.due_at){const d=new Date(t.due_at);if(t.recurrence==='daily')d.setDate(d.getDate()+1);if(t.recurrence==='weekly')d.setDate(d.getDate()+7);if(t.recurrence==='monthly')d.setMonth(d.getMonth()+1);const {data,error}=await supabase.from('tasks').insert({title:t.title,priority:t.priority,due_at:d.toISOString(),category:t.category,recurrence:t.recurrence,user_id:session.user.id}).select().single();if(!error&&data)next=data}setPersonalTasks(prev=>[...(next?[next]:[]),...prev.map(x=>x.id===t.id?{...x,status:done?'done':'pending'} as Task:x)]);if(done)activity('task','Tarefa concluída: '+t.title+(next?' · próxima ocorrência criada':''))}
 async function addReminder(){if(!rt.trim()||!ra)return;setError('');const when=new Date(ra);if(Number.isNaN(when.getTime())){setError('Data do lembrete inválida.');return}const {data,error:e}=await supabase.from('reminders').insert({title:rt.trim(),remind_at:when.toISOString(),user_id:session.user.id}).select().single();if(e||!data){setError('Não foi possível criar o lembrete.');return}setReminders([...reminders,data].sort((a,b)=>a.remind_at.localeCompare(b.remind_at)));activity('reminder','Lembrete criado: '+rt.trim());setRt('');setRa('')}
 async function toggleReminder(r:Reminder){const done=!r.done;const {error:e}=await supabase.from('reminders').update({done}).eq('id',r.id);if(e){setError('Não foi possível atualizar o lembrete.');return}setReminders(reminders.map(x=>x.id===r.id?{...x,done}:x));if(done)activity('reminder','Lembrete concluído: '+r.title)}
 async function snoozeReminder(r:Reminder,minutes:number){const remind_at=new Date(Date.now()+minutes*60000).toISOString();const {error:e}=await supabase.from('reminders').update({remind_at,done:false}).eq('id',r.id);if(e){setError('Não foi possível adiar o lembrete.');return}setReminders(reminders.map(x=>x.id===r.id?{...x,remind_at,done:false}:x).sort((a,b)=>a.remind_at.localeCompare(b.remind_at)));activity('reminder','Lembrete adiado: '+r.title)}
 async function addEvent(){if(!et.trim()||!ea)return;setError('');const starts=new Date(ea),ends=ee?new Date(ee):null;if(Number.isNaN(starts.getTime())||(ends&&Number.isNaN(ends.getTime()))){setError('Data do compromisso inválida.');return}if(ends&&ends.getTime()<starts.getTime()){setError('O término não pode ser antes do início.');return}const {data,error:e}=await supabase.from('calendar_events').insert({title:et.trim(),starts_at:starts.toISOString(),ends_at:ends?ends.toISOString():null,notes:en.trim()||null,user_id:session.user.id}).select().single();if(e||!data){setError('Não foi possível criar o compromisso.');return}setEvents([...events,data].sort((a,b)=>a.starts_at.localeCompare(b.starts_at)));activity('calendar','Compromisso criado: '+et.trim());setEt('');setEa('');setEe('');setEn('')}
 async function editEvent(e:Event){editor.open({title:'Editar compromisso',fields:[{name:'title',label:'Compromisso',value:e.title,required:true},{name:'starts_at',label:'Início',value:localInput(e.starts_at),type:'datetime-local',required:true},{name:'ends_at',label:'Término',value:localInput(e.ends_at),type:'datetime-local'},{name:'notes',label:'Observações',value:e.notes,type:'textarea'}],save:async v=>{const start=iso(v.starts_at),end=iso(v.ends_at);if(!start||end&&end<start)throw new Error('O término precisa ser posterior ao início.');await persist('calendar_events',e.id,{title:v.title.trim(),starts_at:start,ends_at:end,notes:v.notes.trim()||null});void activity('calendar','Compromisso editado: '+v.title)}})}
 async function rescheduleEvent(e:Event,days:number){const starts=new Date(e.starts_at);starts.setDate(starts.getDate()+days);let ends=e.ends_at?new Date(e.ends_at):null;if(ends)ends.setDate(ends.getDate()+days);const {error:failure}=await supabase.from('calendar_events').update({starts_at:starts.toISOString(),ends_at:ends?.toISOString()||null}).eq('id',e.id);if(failure){setError('Não foi possível reagendar o compromisso. Tente novamente.');return}setEvents(events.map(x=>x.id===e.id?{...x,starts_at:starts.toISOString(),ends_at:ends?.toISOString()||null}:x).sort((a,b)=>a.starts_at.localeCompare(b.starts_at)));activity('calendar','Compromisso reagendado: '+e.title)}
 async function addSale(){setError('');const amount=Number(sa.replace(',','.'));if(!sd.trim()){setError('Informe o produto ou a descrição da venda.');return}if(!Number.isFinite(amount)||amount<=0){setError('Informe um valor de venda maior que zero.');return}const {data,error:e}=await supabase.from('sales').insert({customer:sc.trim()||null,description:sd.trim(),amount,sold_at:localDateKey(),notes:saleNotes.trim()||null,user_id:session.user.id}).select().single();if(e||!data){setError('Não foi possível registrar a venda.');return}setSales([data,...sales]);activity('sale','Venda registrada: '+sd.trim());setSc('');setSd('');setSa('');setSaleNotes('')}
 async function editSale(s:Sale){editor.open({title:'Editar venda',fields:[{name:'customer',label:'Cliente',value:s.customer},{name:'description',label:'Produto ou descrição',value:s.description,required:true},{name:'amount',label:'Valor (R$)',value:s.amount,type:'number',min:0.01,required:true},{name:'sold_at',label:'Data da venda',value:s.sold_at,type:'date',required:true},{name:'notes',label:'Observações',value:s.notes,type:'textarea'}],save:async v=>{const amount=Number(v.amount);if(!Number.isFinite(amount)||amount<=0||!validDateKey(v.sold_at))throw new Error('Confira o valor e a data da venda.');await persist('sales',s.id,{customer:v.customer.trim()||null,description:v.description.trim(),amount,sold_at:v.sold_at,notes:v.notes.trim()||null});void activity('sale','Venda editada: '+v.description)}})}
 async function capture(){if(!quick.trim())return;setError('');const {data,error:e}=await supabase.from('inbox').insert({content:quick.trim(),user_id:session.user.id}).select().single();if(e||!data){setError('Não foi possível salvar a captura.');return}setInbox([data,...inbox]);activity('inbox','Captura rápida adicionada: '+quick.trim());setQuick('')}
 async function toggleInbox(i:InboxItem){const processed=!i.processed;const {error:e}=await supabase.from('inbox').update({processed}).eq('id',i.id);if(e){setError('Não foi possível atualizar a captura.');return}setInbox(inbox.map(x=>x.id===i.id?{...x,processed}:x))}
 async function markInboxProcessed(i:InboxItem){const {error:e}=await supabase.from('inbox').update({processed:true}).eq('id',i.id);if(e){setError('O item foi criado, mas a captura não pôde ser marcada como processada.');return false}setInbox(prev=>prev.map(x=>x.id===i.id?{...x,processed:true}:x));return true}
 async function inboxToTask(i:InboxItem){const {data,error:e}=await supabase.from('tasks').insert({title:i.content,user_id:session.user.id}).select().single();if(e||!data){setError('Não foi possível converter a captura em tarefa.');return}setPersonalTasks(prev=>[data,...prev]);await markInboxProcessed(i);activity('task','Captura convertida em tarefa: '+i.content)}
 async function inboxToReminder(i:InboxItem){editor.open({title:'Transformar em lembrete',fields:[{name:'title',label:'Lembrete',value:i.content,required:true},{name:'remind_at',label:'Quando lembrar?',type:'datetime-local',required:true}],submitLabel:'Criar lembrete',save:async v=>{const {error:failure}=await supabase.from('reminders').insert({title:v.title,remind_at:iso(v.remind_at),user_id:session.user.id});if(failure)throw new Error('Não foi possível criar o lembrete.');await markInboxProcessed(i);await load()}})}
 async function inboxToNote(i:InboxItem){editor.open({title:'Transformar em nota',fields:[{name:'title',label:'Título',value:i.content.slice(0,60),required:true},{name:'content',label:'Anotação',value:i.content,type:'textarea'}],submitLabel:'Criar nota',save:async v=>{const {error:failure}=await supabase.from('notes').insert({title:v.title,content:v.content,user_id:session.user.id});if(failure)throw new Error('Não foi possível criar a nota.');await markInboxProcessed(i);await load()}})}
 async function addNote(){if(!nt.trim())return;const {data,error:e}=await supabase.from('notes').insert({title:nt.trim(),content:nc.trim(),user_id:session.user.id}).select().single();if(e||!data){setError('Não foi possível salvar a nota.');return}setNotes([data,...notes]);activity('note','Nota criada: '+nt.trim());setNt('');setNc('')}
 async function togglePin(n:Note){const pinned=!n.pinned;const {error:e}=await supabase.from('notes').update({pinned}).eq('id',n.id);if(e){setError('Não foi possível atualizar a nota.');return}setNotes(notes.map(x=>x.id===n.id?{...x,pinned}:x));activity('note',(pinned?'Nota fixada: ':'Nota desafixada: ')+n.title)}
 async function editNote(n:Note){editor.open({title:'Editar anotação',fields:[{name:'title',label:'Título',value:n.title,required:true},{name:'content',label:'Anotação',value:n.content,type:'textarea',maxLength:10000}],save:async v=>{await persist('notes',n.id,{title:v.title.trim(),content:v.content});void activity('note','Nota editada: '+v.title)}})}
 async function addContact(){if(!cn.trim())return;const next=cnext?new Date(cnext):null;if(next&&Number.isNaN(next.getTime())){setError('Data do retorno inválida.');return}const {data,error:e}=await supabase.from('contacts').insert({name:cn.trim(),phone:cp.trim()||null,company:cc.trim()||null,next_contact_at:next?next.toISOString():null,notes:cnotes.trim()||null,user_id:session.user.id}).select().single();if(e||!data){setError('Não foi possível salvar o contato.');return}setContacts([data,...contacts]);activity('contact','Contato criado: '+cn.trim());setCn('');setCp('');setCc('');setCnext('');setCnotes('')}
 async function editContact(c:Contact){editor.open({title:'Editar contato',fields:[{name:'name',label:'Nome',value:c.name,required:true},{name:'phone',label:'Telefone',value:c.phone,type:'tel'},{name:'company',label:'Empresa',value:c.company},{name:'next_contact_at',label:'Próximo retorno',value:localInput(c.next_contact_at),type:'datetime-local'},{name:'notes',label:'Observações',value:c.notes,type:'textarea'}],save:async v=>{await persist('contacts',c.id,{name:v.name.trim(),phone:v.phone.trim()||null,company:v.company.trim()||null,next_contact_at:iso(v.next_contact_at),notes:v.notes});void activity('contact','Contato editado: '+v.name)}})}
 async function rescheduleContact(c:Contact,days:number){const base=c.next_contact_at&&new Date(c.next_contact_at).getTime()>Date.now()?new Date(c.next_contact_at):new Date();base.setDate(base.getDate()+days);const next_contact_at=base.toISOString();const {error:e}=await supabase.from('contacts').update({next_contact_at}).eq('id',c.id);if(e){setError('Não foi possível reagendar o retorno.');return}setContacts(contacts.map(x=>x.id===c.id?{...x,next_contact_at}:x));activity('contact','Retorno reagendado: '+c.name)}
 async function addGoal(){if(!gt.trim())return;const target=gv.trim()?Number(gv.replace(',','.')):null;if(target!==null&&(!Number.isFinite(target)||target<=0)){setError('O objetivo da meta deve ser maior que zero.');return}const {data,error:e}=await supabase.from('goals').insert({title:gt.trim(),target,period:goalPeriod,user_id:session.user.id}).select().single();if(e||!data){setError('Não foi possível criar a meta.');return}setGoals([data,...goals]);activity('goal','Meta criada: '+gt.trim());setGt('');setGv('');setGoalPeriod('monthly')}
 async function updateGoal(g:Goal,delta:number){const current=Math.max(0,Number(g.current||0)+delta);const {error:e}=await supabase.from('goals').update({current}).eq('id',g.id);if(e){setError('Não foi possível atualizar a meta.');return}setGoals(goals.map(x=>x.id===g.id?{...x,current}:x));activity('goal','Progresso atualizado: '+g.title+' = '+current)}
 async function setGoalProgress(g:Goal){await editGoal(g)}
 async function editGoal(g:Goal){editor.open({title:'Editar meta',fields:[{name:'title',label:'Meta',value:g.title,required:true},{name:'target',label:'Objetivo',value:g.target,type:'number',min:0.01},{name:'current',label:'Progresso atual',value:g.current,type:'number',min:0,required:true},{name:'period',label:'Período',value:g.period,options:[['daily','Diário'],['weekly','Semanal'],['monthly','Mensal'],['yearly','Anual']]}],save:async v=>{const target=v.target?Number(v.target):null,current=Number(v.current);if(!Number.isFinite(current)||current<0||target!==null&&(!Number.isFinite(target)||target<=0))throw new Error('Revise o objetivo e o progresso.');await persist('goals',g.id,{title:v.title.trim(),target,current,period:v.period});void activity('goal','Meta editada: '+v.title)}})}
 async function remove(table:string,id:string){if(!confirm('Tem certeza que deseja excluir?'))return;setError('');const {error:e}=await supabase.from(table).delete().eq('id',id);if(e){setError('Não foi possível excluir. Tente novamente.');return}await load()}
 const pending=tasks.filter(t=>t.status==='pending'),completed=tasks.filter(t=>t.status==='done').length,today=localDateKey(),month=today.slice(0,7),now=Date.now(),todaySales=useMemo(()=>sales.filter(s=>s.sold_at===today).reduce((a,s)=>a+Number(s.amount),0),[sales,today]),monthSales=useMemo(()=>sales.filter(s=>s.sold_at.startsWith(month)).reduce((a,s)=>a+Number(s.amount),0),[sales,month]),filteredSales=useMemo(()=>sales.filter(s=>(salePeriod==='all'||(salePeriod==='today'?s.sold_at===today:s.sold_at.startsWith(month)))&&(!saleSearch||((s.customer||'')+' '+s.description+' '+(s.notes||'')).toLowerCase().includes(saleSearch.toLowerCase()))),[sales,salePeriod,saleSearch,today,month]),filteredSalesTotal=useMemo(()=>filteredSales.reduce((a,s)=>a+Number(s.amount),0),[filteredSales]),overdueTasks=pending.filter(t=>t.due_at&&new Date(t.due_at).getTime()<now),priorityTasks=pending.slice().sort((a,b)=>{const score=(t:Task)=>(t.due_at&&new Date(t.due_at).getTime()<now?100:0)+(t.priority==='high'?30:t.priority==='normal'?10:0)+(t.due_at?Math.max(0,20-Math.floor((new Date(t.due_at).getTime()-now)/86400000)):0);return score(b)-score(a)}).slice(0,5),searchResults=useMemo(()=>{const q=globalSearch.trim().toLowerCase();if(!q)return[];return [...tasks.map(x=>({view:'tasks' as View,title:x.title,meta:'Tarefa · '+(x.category||x.priority)})),...reminders.map(x=>({view:'reminders' as View,title:x.title,meta:'Lembrete · '+fmt(x.remind_at)})),...events.map(x=>({view:'calendar' as View,title:x.title,meta:'Agenda · '+fmt(x.starts_at)})),...notes.map(x=>({view:'notes' as View,title:x.title,meta:'Nota · '+x.content})),...contacts.map(x=>({view:'contacts' as View,title:x.name,meta:'Contato · '+[x.company,x.phone].filter(Boolean).join(' · ')})),...sales.map(x=>({view:'sales' as View,title:x.description,meta:'Venda · '+(x.customer||'')}))].filter(x=>(x.title+' '+x.meta).toLowerCase().includes(q)).slice(0,12)},[globalSearch,tasks,reminders,events,notes,contacts,sales]),todayEvents=events.filter(e=>localDateKey(new Date(e.starts_at))===today),overdueReminders=reminders.filter(r=>!r.done&&new Date(r.remind_at).getTime()<now),dueContacts=contacts.filter(c=>c.next_contact_at&&new Date(c.next_contact_at).getTime()<=now),filteredContacts=contacts.filter(c=>!contactSearch||([c.name,c.company,c.phone,c.notes].filter(Boolean).join(' ').toLowerCase().includes(contactSearch.toLowerCase())))
 if(busy&&!session)return <main className="login"><section className="loginCard"><div className="brandMark">A</div><h1>ArtOrganiz</h1><p>Carregando...</p></section></main>
 if(!session)return <main className="login"><section className="loginCard"><div className="brandMark">A</div><h1>ArtOrganiz</h1><p>Seu dia, seus negócios. Tudo conectado.</p><form onSubmit={login}><input type="email" aria-label="Seu e-mail" autoComplete="username" placeholder="Seu e-mail" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" aria-label="Sua senha" autoComplete="current-password" placeholder="Sua senha" value={password} onChange={e=>setPassword(e.target.value)} required/><button disabled={busy}>{busy?'Aguarde...':'Entrar'}</button>{error&&<small className="error">{error}</small>}</form></section></main>
 return <div className="shell"><aside><div className="logo"><span><Layers3 size={22}/></span><div><b>ArtOrganiz</b><small>Sua central de tudo</small></div></div><p className="navLabel">ESPAÇO DE TRABALHO</p><nav aria-label="Navegação principal">{menu.map(([id,label,Icon])=><button key={id} aria-current={view===id?'page':undefined} className={view===id?'active':''} onClick={()=>setView(id)}><Icon size={19}/>{label}</button>)}</nav><div className="sidebarNote"><span className="statusDot"/>Organize. Acompanhe. Realize.<small>Seu trabalho em um só lugar.</small></div><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut size={18}/>Sair</button></aside><main className="content">{error&&<div className="appError" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>}<AppExperience offlineFinance={view==='finance'} lastRead={lastRead} busy={busy||nexusSales.status==='loading'} refresh={()=>{void load();void refreshHub();void nexusSales.refresh()}}/><header><div><p className="eyebrow">SEU ESPAÇO, SUAS PRIORIDADES</p><h1>{view==='client'?'Visão do cliente':menu.find(x=>x[0]===view)?.[1]}</h1></div><div className="headerAccount"><span>{new Date().toLocaleDateString('pt-BR',{day:'numeric',month:'long'})}</span><div className="avatar" title={session.user.email}>{(session.user.email||'A').slice(0,1).toUpperCase()}</div></div></header><section className="globalSearch"><Search size={18} aria-hidden="true"/><input aria-label="Buscar na central" value={globalSearch} onChange={e=>setGlobalSearch(e.target.value)} placeholder="Encontre uma tarefa, contato, nota ou venda..."/>{globalSearch&&<div className="searchResults">{searchResults.length?searchResults.map((r,i)=><button key={i} onClick={()=>{setView(r.view);setGlobalSearch('')}}><strong>{r.title}</strong><small>{r.meta}</small></button>):<p className="muted">Nenhum resultado.</p>}</div>}</section>
 {view==='today'&&<div className="dashboard">
 <section className="hero"><div><p className="heroKicker">UM NOVO DIA. NOVAS POSSIBILIDADES.</p><h2>Seu dia, no seu ritmo.</h2><span>{overdueTasks.length+overdueReminders.length+dueContacts.length>0?`${overdueTasks.length+overdueReminders.length+dueContacts.length} pendências precisam da sua atenção.`:'Tudo pronto para focar no que importa.'} Vamos organizar as próximas ações?</span><div className="heroActions"><button onClick={()=>setView('tasks')}><Plus size={17}/> Nova tarefa</button><button onClick={()=>setView('nexus')}>Abrir Nexus <ArrowUpRight size={17}/></button></div></div><div className="dayProgress"><div className="progressRing" style={{'--progress':`${tasks.length?Math.round(completed/tasks.length*100):0}%`} as React.CSSProperties}><strong>{tasks.length?Math.round(completed/tasks.length*100):0}<small>%</small></strong></div><span>tarefas concluídas</span><small>{completed} de {tasks.length} tarefas</small></div></section>
 <div className="stats overviewStats"><button onClick={()=>setView('tasks')}><span><ListTodo size={17}/> A fazer</span><strong>{pending.length}</strong><small>{overdueTasks.length?`${overdueTasks.length} atrasadas`:'Suas próximas entregas'}</small></button><button onClick={()=>setView('calendar')}><span><CalendarDays size={17}/> Agenda de hoje</span><strong>{todayEvents.length}</strong><small>Compromissos do dia</small></button><button onClick={()=>setView('sales')}><span><CircleDollarSign size={17}/> Vendas no mês · Nexus</span><strong>{nexusSales.status==='ready'?orderTotal(salesForPeriod(nexusSales.orders,today,'month')).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):nexusSales.status==='loading'?'Carregando…':'—'}</strong><small>{nexusSales.status==='ready'?'Hoje: '+orderTotal(salesForPeriod(nexusSales.orders,today,'today')).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):nexusSales.status==='disconnected'?'Conecte o Nexus':nexusSales.status==='error'?'Falha na consulta · abrir para atualizar':'Consultando pedidos'}</small></button><button onClick={()=>setView('contacts')}><span><Users size={17}/> Retornos pendentes</span><strong>{dueContacts.length}</strong><small>Conversas para retomar</small></button></div>
 <div className="quickActions"><button onClick={()=>setView('pending')}><Bell size={17}/> Central de pendências</button><button onClick={()=>setView('reminders')}><Bell size={17}/> Lembrete</button><button onClick={()=>setView('calendar')}><CalendarDays size={17}/> Compromisso</button><button onClick={()=>setView('sales')}><CircleDollarSign size={17}/> Registrar venda</button><button onClick={()=>setView('inbox')}><Inbox size={17}/> Capturar ideia</button><button onClick={()=>setView('notes')}><NotebookPen size={17}/> Nova nota</button></div>
 <div className="workspaceGrid"><section className="panel"><div className="panelHead"><div><p className="eyebrow">UM PASSO DE CADA VEZ</p><h2>Seu foco agora</h2></div><button className="textLink" onClick={()=>setView('tasks')}>Ver tarefas <ArrowUpRight size={16}/></button></div><div className="taskList">{priorityTasks.length?priorityTasks.map(t=><button className={'task '+(t.priority==='high'?'priorityTask':'')} key={t.id} onClick={()=>toggle(t)} aria-label={'Concluir tarefa: '+t.title}><CheckCircle2 size={20}/><span>{t.title}</span><small>{t.priority==='high'?'Alta prioridade':t.due_at?fmt(t.due_at):'Sem prazo'}</small></button>):<div className="calmEmpty"><CheckCircle2 size={30}/><h3>Espaço para o próximo passo</h3><p>Adicione uma tarefa e comece pelo que importa.</p><button onClick={()=>setView('tasks')}>Criar primeira tarefa</button></div>}</div></section>
 <section className="panel"><div className="panelHead"><div><p className="eyebrow">SUA PROGRAMAÇÃO</p><h2>Na agenda</h2></div><button className="textLink" onClick={()=>setView('calendar')}>Ver agenda <ArrowUpRight size={16}/></button></div><div className="agendaList">{todayEvents.length?todayEvents.slice(0,4).map(e=><div className="agendaItem" key={e.id}><time>{new Date(e.starts_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time><div><strong>{e.title}</strong><small>{e.notes||'Compromisso de hoje'}</small></div></div>):<div className="calmEmpty"><CalendarDays size={30}/><h3>Hoje está livre</h3><p>Reserve um momento para suas prioridades.</p><button onClick={()=>setView('calendar')}>Agendar compromisso</button></div>}</div></section></div>
 {(overdueReminders.length>0||dueContacts.length>0)&&<section className="followups"><div><Bell size={20}/><strong>Não deixe para depois</strong></div>{overdueReminders.length>0&&<button onClick={()=>setView('reminders')}>{overdueReminders.length} lembretes vencidos <ArrowUpRight size={15}/></button>}{dueContacts.length>0&&<button onClick={()=>setView('contacts')}>{dueContacts.length} contatos aguardam retorno <ArrowUpRight size={15}/></button>}</section>}
 <section className="nexusLaunch"><div className="nexusSymbol"><Layers3 size={25}/></div><div><p className="eyebrow">NEGÓCIOS CONECTADOS</p><h3>Nexus, dentro da sua central.</h3><p>Clientes, pedidos e oportunidades ao alcance de um clique.</p></div><button onClick={()=>setView('nexus')}>Gerenciar Nexus <ArrowUpRight size={17}/></button></section>
 <div className="workspaceGrid secondaryGrid"><section className="panel"><div className="panelHead"><div><p className="eyebrow">CADA AVANÇO CONTA</p><h2>Suas metas</h2></div><button className="textLink" onClick={()=>setView('goals')}>Ver todas <ArrowUpRight size={16}/></button></div>{goals.length?goals.slice(0,3).map(g=><div className="goalPreview" key={g.id}><div><strong>{g.title}</strong><span>{g.current}{g.target?' / '+g.target:''}</span></div><progress aria-label={'Progresso de '+g.title} value={g.target?Math.min(100,Number(g.current)/Number(g.target)*100):0} max="100"/></div>):<p className="emptyHint">Transforme seus planos em metas e acompanhe cada avanço.</p>}</section><section className="panel"><div className="panelHead"><div><p className="eyebrow">IDEIAS POR PERTO</p><h2>Suas notas</h2></div><button className="textLink" onClick={()=>setView('notes')}>Abrir notas <ArrowUpRight size={16}/></button></div>{notes.length?notes.slice().sort((a,b)=>Number(b.pinned)-Number(a.pinned)).slice(0,3).map(n=><button className="notePreview" key={n.id} onClick={()=>setView('notes')}><NotebookPen size={18}/><div><strong>{n.title}</strong><small>{n.content||'Sem conteúdo'}</small></div><ArrowUpRight size={15}/></button>):<p className="emptyHint">Guarde uma ideia agora. Encontre quando precisar.</p>}</section></div>
 <div className="assistantSection"><div className="sectionTitle"><Sparkles size={20}/><div><h2>Uma ajuda para organizar</h2><p>Crie tarefas, lembretes e notas usando suas palavras.</p></div></div><section className="aiBrief"><div><p className="eyebrow">ASSISTENTE</p><h3>Resumo inteligente do dia</h3><p>{dayBrief||'Analiso suas tarefas, lembretes, agenda e retornos para montar um foco rápido para hoje.'}</p></div><button onClick={generateDayBrief} disabled={briefBusy}><Sparkles size={17}/>{briefBusy?' Analisando...':dayBrief?' Atualizar':' Analisar meu dia'}</button></section><SmartAssistant userId={session.user.id} data={{tasks,reminders,events,contacts,sales,nexus:hubPending}} onChanged={()=>{void load();void refreshHub()}}/></div><button className="notificationLink" onClick={enableNotifications}><Bell size={16}/> Ativar notificações neste dispositivo</button>
 </div>}
 {view==='finance'&&<Suspense fallback={<p role="status">Abrindo o financeiro...</p>}><PersonalFinance key={session.user.id} userId={session.user.id}/></Suspense>}
 {view==='pending'&&<PendingCenter tasks={tasks} reminders={reminders} events={events} contacts={contacts} nexus={hubPending} hasMore={hubMore} loading={busy||hubBusy} error={hubError} onView={setView} onSource={openSource} onToggle={toggle} onReminder={toggleReminder} onTask={createLinked} refresh={()=>{void load();void refreshHub()}}/>}
 {view==='client'&&<Suspense fallback={<p role="status">Abrindo o cliente...</p>}><ClientPage key={clientId} id={clientId} tasks={linkedTasks} onBack={()=>setView('nexus')} onSource={openSource} onTask={createLinked} onChanged={()=>void refreshHub()}/></Suspense>}
 {view==='tasks'&&<TaskPanel tasks={tasks} newTask={newTask} setNewTask={setNewTask} addTask={addTask} toggle={toggle} taskPriority={taskPriority} setTaskPriority={setTaskPriority} taskDue={taskDue} setTaskDue={setTaskDue} taskCategory={taskCategory} setTaskCategory={setTaskCategory} taskRecurrence={taskRecurrence} setTaskRecurrence={setTaskRecurrence} deleteTask={deleteTask} editTask={editTask} openSource={openSource}/>}
 {view==='reminders'&&<Module title="Novo lembrete"><Form><input placeholder="Lembrete" value={rt} onChange={e=>setRt(e.target.value)}/><input type="datetime-local" value={ra} onChange={e=>setRa(e.target.value)}/><button onClick={addReminder}>Adicionar</button></Form>{reminders.map(r=>{const late=!r.done&&new Date(r.remind_at).getTime()<Date.now();return <div key={r.id} className={'dataRow '+(late?'lateRow':'')}><button className={'task '+(r.done?'done':'')} onClick={()=>toggleReminder(r)}><CheckCircle2 size={19}/><span>{r.title}</span><small>{late?'ATRASADO · ':''}{fmt(r.remind_at)}</small></button>{!r.done&&<><button onClick={()=>snoozeReminder(r,60)}>+1h</button><button onClick={()=>snoozeReminder(r,1440)}>Amanhã</button></>}<button className="iconBtn" onClick={()=>remove('reminders',r.id)}><Trash2 size={17}/></button></div>})}</Module>}
 {view==='calendar'&&<Module title="Novo compromisso"><Form><input placeholder="Título" value={et} onChange={e=>setEt(e.target.value)}/><input type="datetime-local" value={ea} onChange={e=>setEa(e.target.value)}/><input type="datetime-local" value={ee} onChange={e=>setEe(e.target.value)} title="Término"/><input placeholder="Observações" value={en} onChange={e=>setEn(e.target.value)}/><button onClick={addEvent}>Adicionar</button></Form>{events.map(e=><div className="dataRow" key={e.id}><div><strong>{e.title}</strong><small>{fmt(e.starts_at)+(e.ends_at?' até '+fmt(e.ends_at):'')+(e.notes?' · '+e.notes:'')}</small></div><button onClick={()=>editEvent(e)}>Editar</button><button onClick={()=>rescheduleEvent(e,1)}>+1 dia</button><button onClick={()=>rescheduleEvent(e,7)}>+7 dias</button><button className="iconBtn" onClick={()=>remove('calendar_events',e.id)}><Trash2 size={17}/></button></div>)}</Module>}
 {view==='sales'&&<NexusSales {...nexusSales} today={today} refresh={()=>void nexusSales.refresh()} connect={()=>setView('nexus')} open={id=>openSource({kind:'orders',id})}/>}
 {view==='sales'&&<Module title="Vendas registradas manualmente"><p className="muted">Registros próprios do ArtOrganiz, separados dos pedidos do Nexus e do Financeiro pessoal.</p><Form><input placeholder="Cliente" value={sc} onChange={e=>setSc(e.target.value)}/><input placeholder="Produto / descrição" value={sd} onChange={e=>setSd(e.target.value)}/><input inputMode="decimal" placeholder="Valor" value={sa} onChange={e=>setSa(e.target.value)}/><input placeholder="Observações" value={saleNotes} onChange={e=>setSaleNotes(e.target.value)}/><button onClick={addSale}>Registrar</button></Form><div className="stats"><article><span>Hoje</span><strong>{todaySales.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong></article><article><span>Mês</span><strong>{monthSales.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong></article><article><span>Filtrado</span><strong>{filteredSalesTotal.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong></article></div><div className="quick"><input placeholder="Buscar cliente, produto ou observação..." value={saleSearch} onChange={e=>setSaleSearch(e.target.value)}/><select value={salePeriod} onChange={e=>setSalePeriod(e.target.value as any)}><option value="today">Hoje</option><option value="month">Este mês</option><option value="all">Tudo</option></select></div>{filteredSales.map(s=><div className="dataRow" key={s.id}><div><strong>{s.description}</strong><small>{(s.customer?s.customer+' · ':'')+Number(s.amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})+' · '+s.sold_at+(s.notes?' · '+s.notes:'')}</small></div><button onClick={()=>editSale(s)}>Editar</button><button className="iconBtn" onClick={()=>remove('sales',s.id)}><Trash2 size={17}/></button></div>)}</Module>}
 {view==='inbox'&&<Module title="Captura rápida"><Form><input placeholder="Digite qualquer coisa para lembrar depois..." value={quick} onChange={e=>setQuick(e.target.value)} onKeyDown={e=>e.key==='Enter'&&capture()}/><button onClick={capture}>Salvar</button></Form>{inbox.map(i=><div key={i.id} className="dataRow"><button className={'task '+(i.processed?'done':'')} onClick={()=>toggleInbox(i)}><CheckCircle2 size={19}/><span>{i.content}</span><small>{i.processed?'Processado':'Pendente'}</small></button>{!i.processed&&<><button onClick={()=>inboxToTask(i)}>Virar tarefa</button><button onClick={()=>inboxToReminder(i)}>Lembrete</button><button onClick={()=>inboxToNote(i)}>Nota</button></>}<button className="iconBtn" onClick={()=>remove('inbox',i.id)}><Trash2 size={17}/></button></div>)}</Module>}
 {view==='notes'&&<Module title="Nova anotação"><Form><input placeholder="Título" value={nt} onChange={e=>setNt(e.target.value)}/><input placeholder="Anotação" value={nc} onChange={e=>setNc(e.target.value)}/><button onClick={addNote}>Salvar</button></Form>{notes.slice().sort((a,b)=>Number(b.pinned)-Number(a.pinned)).map(n=><div className="dataRow" key={n.id}><div><strong>{n.pinned?'📌 '+n.title:n.title}</strong><small>{n.content||'Sem conteúdo'}</small></div><button onClick={()=>togglePin(n)}>{n.pinned?'Desafixar':'Fixar'}</button><button onClick={()=>editNote(n)}>Editar</button><button className="iconBtn" onClick={()=>remove('notes',n.id)}><Trash2 size={17}/></button></div>)}</Module>}
 {view==='contacts'&&<Module title="Novo contato"><Form><input placeholder="Nome" value={cn} onChange={e=>setCn(e.target.value)}/><input placeholder="Telefone" value={cp} onChange={e=>setCp(e.target.value)}/><input placeholder="Empresa" value={cc} onChange={e=>setCc(e.target.value)}/><input type="datetime-local" value={cnext} onChange={e=>setCnext(e.target.value)} title="Próximo retorno"/><input placeholder="Observações" value={cnotes} onChange={e=>setCnotes(e.target.value)}/><button onClick={addContact}>Salvar</button></Form><div className="quick"><input placeholder="Buscar contato, empresa ou telefone..." value={contactSearch} onChange={e=>setContactSearch(e.target.value)}/></div>{filteredContacts.slice().sort((a,b)=>(a.next_contact_at||'9999').localeCompare(b.next_contact_at||'9999')).map(c=>{const late=!!c.next_contact_at&&new Date(c.next_contact_at).getTime()<=Date.now();return <div className={'dataRow '+(late?'lateRow':'')} key={c.id}><div><strong>{c.name}</strong><small>{[late?'RETORNO PENDENTE':null,c.company,c.phone,c.next_contact_at?'Retorno: '+fmt(c.next_contact_at):null,c.notes].filter(Boolean).join(' · ')||'Sem detalhes'}</small></div><button onClick={()=>editContact(c)}>Editar</button><button onClick={()=>rescheduleContact(c,1)}>Amanhã</button><button onClick={()=>rescheduleContact(c,7)}>+7 dias</button><button className="iconBtn" onClick={()=>remove('contacts',c.id)}><Trash2 size={17}/></button></div>})}</Module>}
 {view==='goals'&&<Module title="Nova meta"><Form><input placeholder="Meta" value={gt} onChange={e=>setGt(e.target.value)}/><input inputMode="decimal" placeholder="Objetivo" value={gv} onChange={e=>setGv(e.target.value)}/><select value={goalPeriod} onChange={e=>setGoalPeriod(e.target.value)}><option value="daily">Diária</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option><option value="yearly">Anual</option></select><button onClick={addGoal}>Salvar</button></Form>{goals.map(g=>{const pct=g.target?Math.min(100,Math.round((Number(g.current||0)/Number(g.target))*100)):0;return <div className="dataRow" key={g.id}><div><strong>{g.title}</strong><small>{g.period==='daily'?'Diária':g.period==='weekly'?'Semanal':g.period==='yearly'?'Anual':'Mensal'} · Progresso: {g.current}{g.target?' / '+g.target+' · '+pct+'%':''}{pct>=100?' · META ATINGIDA':''}</small><progress value={pct} max="100"/></div><button onClick={()=>updateGoal(g,-1)}>-1</button><button onClick={()=>updateGoal(g,1)}>+1</button><button onClick={()=>setGoalProgress(g)}>Definir</button><button onClick={()=>editGoal(g)}>Editar</button><button className="iconBtn" onClick={()=>remove('goals',g.id)}><Trash2 size={17}/></button></div>})}</Module>}
 {view==='history'&&<Module title="Atividades recentes">{history.length?history.map(h=><Row key={h.id} title={h.description} meta={fmt(h.created_at)}/>):<p className="muted">Nenhuma atividade registrada.</p>}</Module>}
 {view==='bling'&&<BlingPanel/>}
 {view==='nexus'&&<Suspense fallback={<p role="status">Abrindo o Nexus...</p>}><NexusPanel key={session.user.id+(nexusTarget?.id||'')} initialTarget={nexusTarget} onConnectionChange={nexusSales.refresh} onTask={createLinked} onClient={id=>openSource({kind:'clients',id})}/></Suspense>}
 {editor.element}</main><div className="mobileNav"><button className={view==='today'?'active':''} onClick={()=>{setView('today');setMobileMore(false)}}><LayoutDashboard/><span>Hoje</span></button><button className={view==='tasks'?'active':''} onClick={()=>{setView('tasks');setMobileMore(false)}}><ListTodo/><span>Tarefas</span></button><button className={view==='calendar'?'active':''} onClick={()=>{setView('calendar');setMobileMore(false)}}><CalendarDays/><span>Agenda</span></button><button className={view==='sales'?'active':''} onClick={()=>{setView('sales');setMobileMore(false)}}><CircleDollarSign/><span>Vendas</span></button><button className={mobileMore?'active':''} onClick={()=>setMobileMore(!mobileMore)}>{mobileMore?<X/>:<Menu/>}<span>Mais</span></button></div>{mobileMore&&<div className="moreSheet"><div className="moreGrid">{menu.filter(([id])=>!['today','tasks','calendar','sales'].includes(id)).map(([id,label,Icon])=><button key={id} onClick={()=>{setView(id);setMobileMore(false)}}><Icon size={22}/><span>{label}</span></button>)}</div></div>}</div>}
function localDateKey(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function validDateKey(v:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const [y,m,d]=v.split('-').map(Number),dt=new Date(y,m-1,d);return dt.getFullYear()===y&&dt.getMonth()===m-1&&dt.getDate()===d}
function fmt(v:string){return new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}
function Form({children}:{children:React.ReactNode}){return <div className="formGrid">{children}</div>}
function Module({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><div className="panelHead"><div><p className="eyebrow">ORGANIZAR</p><h2>{title}</h2></div></div>{children}</section>}
function Row({title,meta,del}:{title:string;meta:string;del?:()=>void}){return <div className="dataRow"><div><strong>{title}</strong><small>{meta}</small></div>{del&&<button className="iconBtn" onClick={del}><Trash2 size={17}/></button>}</div>}
function TaskPanel({tasks,newTask,setNewTask,addTask,toggle,taskPriority='normal',setTaskPriority,taskDue='',setTaskDue,taskCategory='',setTaskCategory,taskRecurrence='',setTaskRecurrence,deleteTask,editTask,openSource}:{tasks:Task[];newTask:string;setNewTask:(s:string)=>void;addTask:()=>void;toggle:(t:Task)=>void;taskPriority?:'low'|'normal'|'high';setTaskPriority?:(s:'low'|'normal'|'high')=>void;taskDue?:string;setTaskDue?:(s:string)=>void;taskCategory?:string;setTaskCategory?:(s:string)=>void;taskRecurrence?:string;setTaskRecurrence?:(s:string)=>void;deleteTask?:(t:Task)=>void;editTask?:(t:Task)=>void;openSource?:(s:Source)=>void}){return <section className="panel"><div className="panelHead"><div><p className="eyebrow">FOCO</p><h2>Tarefas</h2></div><div className="quick"><input placeholder="Adicionar tarefa..." value={newTask} onChange={e=>setNewTask(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addTask()}/>{setTaskPriority&&<select value={taskPriority} onChange={e=>setTaskPriority(e.target.value as any)}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option></select>}{setTaskCategory&&<input placeholder="Categoria" value={taskCategory} onChange={e=>setTaskCategory(e.target.value)}/>} {setTaskRecurrence&&<select value={taskRecurrence} onChange={e=>setTaskRecurrence(e.target.value)}><option value="">Sem repetição</option><option value="daily">Diária</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option></select>}{setTaskDue&&<input type="datetime-local" value={taskDue} onChange={e=>setTaskDue(e.target.value)}/>}<button aria-label="Adicionar tarefa" onClick={addTask}><Plus size={18}/></button></div></div><div className="taskList">{tasks.length?tasks.map(t=>{const late=t.status!=='done'&&!!t.due_at&&new Date(t.due_at).getTime()<Date.now();return <div className={'dataRow '+(late?'lateRow':'')} key={t.id}><button className={'task '+(t.status==='done'?'done':'')} onClick={()=>toggle(t)}><CheckCircle2 size={20}/><span>{t.title}</span><small>{late?'ATRASADA · ':''}{t.priority==='high'?'Alta':t.priority==='low'?'Baixa':'Normal'}{t.category?' · '+t.category:''}{t.recurrence?' · '+(t.recurrence==='daily'?'Diária':t.recurrence==='weekly'?'Semanal':'Mensal'):''}{t.due_at?' · '+fmt(t.due_at):''}</small></button>{t.origin==='nexus'&&openSource&&<button onClick={()=>openSource({kind:t.source_kind!,id:t.source_id!})}>Abrir origem</button>}{editTask&&<button onClick={()=>editTask(t)}>Editar</button>}{deleteTask&&<button className="iconBtn" onClick={()=>deleteTask(t)}><Trash2 size={17}/></button>}</div>}):<p className="muted">Tudo em dia por aqui.</p>}</div></section>}
