import { useEffect, useState } from 'react'
import { useRegisterSW } from 'virtual:pwa-register/react'
import { Download, RefreshCw, WifiOff } from 'lucide-react'
export function AppExperience({lastRead,busy,refresh,offlineFinance}:{offlineFinance:boolean;lastRead:string;busy:boolean;refresh:()=>void}){
 const [online,setOnline]=useState(navigator.onLine),[install,setInstall]=useState<any>(null),[help,setHelp]=useState(false),[standalone,setStandalone]=useState(()=>window.matchMedia('(display-mode: standalone)').matches)
 const [registration,setRegistration]=useState<ServiceWorkerRegistration>()
 const {needRefresh:[needRefresh],updateServiceWorker}=useRegisterSW({onRegisteredSW(_url,r){if(r)setRegistration(r)}})
 useEffect(()=>{if(!registration)return;const check=()=>{if(document.visibilityState==='visible'&&navigator.onLine)void registration.update().catch(()=>{})};document.addEventListener('visibilitychange',check);return()=>document.removeEventListener('visibilitychange',check)},[registration])
 useEffect(()=>{const change=()=>setOnline(navigator.onLine),prompt=(e:Event)=>{e.preventDefault();setInstall(e)},installed=()=>{setInstall(null);setStandalone(true)};window.addEventListener('online',change);window.addEventListener('offline',change);window.addEventListener('beforeinstallprompt',prompt);window.addEventListener('appinstalled',installed);return()=>{window.removeEventListener('online',change);window.removeEventListener('offline',change);window.removeEventListener('beforeinstallprompt',prompt);window.removeEventListener('appinstalled',installed)}},[])
 async function installApp(){if(install){await install.prompt();const result=await install.userChoice;if(result.outcome==='accepted')setInstall(null)}else setHelp(v=>!v)}
 return <><div className="experienceBar"><span className={!online?'offlineLabel':''}>{!online?<><WifiOff size={14}/>Sem conexão — os dados podem estar desatualizados</>:busy?'Atualizando seus dados...':lastRead?'Atualizado às '+new Date(lastRead).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'Carregando seus dados...'}</span><div><button disabled={!online||busy} onClick={refresh} aria-label="Atualizar central"><RefreshCw size={15}/></button>{!standalone&&<button onClick={()=>void installApp()}><Download size={14}/>Instalar app</button>}</div></div>{help&&<p className="installHelp">No celular, abra o menu do navegador e escolha “Adicionar à tela inicial” ou “Instalar aplicativo”. No iPhone, use Compartilhar → Adicionar à Tela de Início.</p>}{needRefresh&&<div className="updateBanner" role="status"><span>Uma nova versão do ArtOrganiz está pronta. Salve suas edições antes de atualizar.</span><button onClick={()=>void updateServiceWorker(true)}>Atualizar aplicativo</button></div>}{!online&&<p className="offlineBanner" role="status">{offlineFinance?'O Financeiro pessoal funciona offline neste dispositivo. Mantenha um backup dos seus lançamentos.':'Reconecte antes de salvar alterações. Seus dados comerciais não são armazenados para consulta offline.'}</p>}</>
}
