import { useEffect,useState } from 'react'
import { Building2,CheckCircle2,Cloud,Package,RefreshCw,ShoppingBag,Users,WalletCards } from 'lucide-react'
import './BlingPanel.css'
type Status={configured:boolean;connected:boolean;expiresAt:number|null;scope:string|null}
type Summary={syncedAt:string;summary:Record<string,{count:number|null;unavailable?:boolean}>}
const cards=[['orders','Pedidos',ShoppingBag],['contacts','Clientes',Users],['products','Produtos',Package],['receivables','A receber',WalletCards],['payables','A pagar',WalletCards]] as const
const messages:Record<string,string>={connected:'Bling conectado com sucesso.',denied:'A autorização foi cancelada no Bling.',invalid:'A autorização expirou. Tente conectar novamente.',error:'Não foi possível concluir a conexão com o Bling.',config:'As credenciais do aplicativo Bling ainda precisam ser configuradas.'}
export function BlingPanel(){
 const[status,setStatus]=useState<Status|null>(null),[summary,setSummary]=useState<Summary|null>(null),[busy,setBusy]=useState(true),[notice,setNotice]=useState('')
 async function sync(){setBusy(true);try{const response=await fetch('/api/bling/summary');if(!response.ok)throw Error();setSummary(await response.json());setNotice('Dados empresariais atualizados.')}catch{setNotice('Não foi possível atualizar o Bling agora.')}finally{setBusy(false)}}
 async function load(){setBusy(true);try{const response=await fetch('/api/bling/status'),data=await response.json() as Status;setStatus(data);if(data.connected)await sync()}catch{setNotice('Não foi possível conferir a integração.');setBusy(false)}}
 async function disconnect(){await fetch('/api/bling/disconnect',{method:'POST'});setStatus(s=>s?{...s,connected:false}:s);setSummary(null);setNotice('Bling desconectado deste dispositivo.')}
 useEffect(()=>{const value=new URLSearchParams(location.search).get('bling');if(value&&messages[value])setNotice(messages[value]);if(location.search)history.replaceState({},'',location.pathname);void load()},[])
 return <div className="blingPage">
  <section className="blingHero"><div className="blingHeroIcon"><Building2 size={30}/></div><div><p className="eyebrow">EMPRESA CONECTADA</p><h2>Bling no ArtOrganiz</h2><p>Pedidos, clientes, produtos e financeiro empresarial reunidos sem misturar com suas finanças pessoais.</p></div><span className={'blingStatus '+(status?.connected?'connected':'')}>{busy&&!status?'Verificando':status?.connected?'Conectado':'Desconectado'}</span></section>
  {notice&&<button className="blingNotice" onClick={()=>setNotice('')}><CheckCircle2 size={17}/>{notice}</button>}
  {!busy&&!status?.connected&&<section className="panel blingConnect"><Cloud size={34}/><div><h3>{status?.configured?'Autorize sua conta do Bling':'Configuração inicial pendente'}</h3><p>{status?.configured?'Você será levado ao Bling para autorizar somente os módulos escolhidos.':'Cadastre o ArtOrganiz na Área do Integrador do Bling e adicione as credenciais protegidas na Vercel.'}</p><small>URL de redirecionamento: <strong>https://artorganiz-app.vercel.app/api/bling/callback</strong></small></div><a className={!status?.configured?'disabled':''} href="/api/bling/connect">Conectar Bling</a></section>}
  {status?.connected&&<><div className="blingActions"><div><p className="eyebrow">RESUMO EMPRESARIAL</p><h3>Dados do Bling</h3></div><button onClick={sync} disabled={busy}><RefreshCw className={busy?'spin':''} size={16}/>{busy?'Atualizando...':'Atualizar agora'}</button></div><div className="blingGrid">{cards.map(([key,label,Icon])=>{const item=summary?.summary[key];return <article key={key}><Icon size={20}/><span>{label}</span><strong>{item?.count??'—'}</strong>{item?.unavailable&&<small>Escopo sem acesso</small>}</article>})}</div><section className="panel blingFoot"><div><strong>Sincronização somente de leitura</strong><p>O ArtOrganiz consulta seus dados. Nenhuma alteração é enviada ao Bling nesta primeira etapa.</p>{summary?.syncedAt&&<small>Última atualização: {new Date(summary.syncedAt).toLocaleString('pt-BR')}</small>}</div><button onClick={disconnect}>Desconectar</button></section></>}
  <section className="blingSeparation"><WalletCards size={24}/><div><strong>Financeiro pessoal preservado</strong><p>Os lançamentos pessoais continuam isolados. Os números do Bling aparecem apenas neste módulo empresarial.</p></div></section>
 </div>
}
