import { useEffect, useState } from 'react'
import { ArrowLeft, NotebookPen, CalendarDays, RefreshCw } from 'lucide-react'
import { hub, fmt, money, iso, localInput } from './hub'
import type { Source, LinkedTask } from './hub'
import { useEditor } from './Editor'
export function ClientPage({id,onBack,onSource,onTask,tasks,onChanged}:{id:string;onBack:()=>void;onSource:(s:Source)=>void;onTask:(s:Source)=>void;tasks:LinkedTask[];onChanged:()=>void}){
 const [data,setData]=useState<any>(null),[orders,setOrders]=useState<any[]>([]),[interests,setInterests]=useState<any[]>([]),[cursors,setCursors]=useState<Record<string,string|null>>({}),[totals,setTotals]=useState<Record<string,number>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0)
 const editor=useEditor()
 useEffect(()=>{let active=true;setBusy(true);setError('');Promise.all([hub('client',{id}),hub('client_orders',{id}),hub('client_interests',{id})]).then(([d,o,i])=>{if(!active)return;setData(d);setOrders(o.items);setInterests(i.items);setCursors({orders:o.nextCursor,interests:i.nextCursor});setTotals({orders:o.total,interests:i.total})}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[id,version])
 async function more(kind:'orders'|'interests'){setBusy(true);setError('');try{const r=await hub('client_'+kind,{id,cursor:cursors[kind]});(kind==='orders'?setOrders:setInterests)(prev=>[...prev,...r.items]);setCursors(prev=>({...prev,[kind]:r.nextCursor}))}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar.')}finally{setBusy(false)}}
 function editMemo(){editor.open({title:'Anotações e próximo retorno',description:'Estas informações são pessoais da sua conta ArtOrganiz.',fields:[{name:'notes',label:'Anotações sobre o cliente',type:'textarea',value:data.workspace.notes,maxLength:3000},{name:'next_contact_at',label:'Próximo retorno',type:'datetime-local',value:localInput(data.workspace.next_contact_at)}],save:async v=>{const r=await hub('save_client',{id,notes:v.notes,next_contact_at:iso(v.next_contact_at),expected:data.workspace.updated_at||null});setData((p:any)=>({...p,workspace:r.workspace}));onChanged()}})}
 const client=data?.client,name=client?.trade_name||client?.company_name||client?.contact_name||'Cliente',linked=tasks.filter(t=>t.source_kind==='clients'&&t.source_id===id)
 return <section className="clientPage"><div className="moduleToolbar"><button onClick={onBack}><ArrowLeft size={16}/>Voltar</button><button disabled={busy} onClick={()=>setVersion(v=>v+1)}><RefreshCw size={16}/>Atualizar</button></div>{error&&<p className="formError" role="alert">{error}</p>}{busy&&!data&&<p role="status">Carregando o cliente...</p>}{data&&<><section className="panel clientIdentity"><div className="clientMonogram">{name.slice(0,1).toUpperCase()}</div><div><p className="eyebrow">CLIENTE NEXUS</p><h2>{name}</h2><p>{[client.contact_name,client.city,client.state].filter(Boolean).join(' · ')}</p><div className="contactLinks">{client.phone&&<a href={'tel:'+String(client.phone).replace(/[^+\d]/g,'')}>{client.phone}</a>}{client.email&&<a href={'mailto:'+client.email}>{client.email}</a>}</div></div><button onClick={()=>onTask({kind:'clients',id,title:name})}>Agendar tarefa</button></section><div className="clientStats"><div><span>Pedidos</span><strong>{totals.orders||0}</strong></div><div><span>Interesses</span><strong>{totals.interests||0}</strong></div><div><span>Próximo retorno</span><strong className="dateValue">{data.workspace.next_contact_at?fmt(data.workspace.next_contact_at):'Não agendado'}</strong></div></div><section className="panel"><div className="panelHead"><h2><NotebookPen size={18}/> Anotações e acompanhamento</h2><button onClick={editMemo}>Editar anotações / retorno</button></div><p className="clientNotes">{data.workspace.notes||'Registre preferências e detalhes importantes para o próximo contato.'}</p>{linked.map(t=><div className="dataRow" key={t.id}><strong>{t.title}</strong><small>{t.status==='done'?'Concluída':fmt(t.due_at)}</small></div>)}</section><div className="workspaceGrid"><section className="panel"><h2>Pedidos do cliente</h2>{orders.length?orders.map(o=><div className="clientRecord" key={o.id}><button onClick={()=>onSource({kind:'orders',id:o.id})}><strong>{o.order_number}</strong><small>{o.status} · {money(o.total)}</small></button><button onClick={()=>onTask({kind:'orders',id:o.id,title:o.order_number})}>Criar tarefa</button></div>):<p className="emptyHint">Nenhum pedido cadastrado.</p>}{cursors.orders&&<button disabled={busy} onClick={()=>void more('orders')}>Carregar mais pedidos</button>}</section><section className="panel"><h2>Interesses do cliente</h2>{interests.length?interests.map(i=><div className="clientRecord" key={i.id}><button onClick={()=>onSource({kind:'interests',id:i.id})}><strong>{i.requested_product}</strong><small>{i.status} · {i.desired_quantity||'—'} unidades</small></button><button onClick={()=>onTask({kind:'interests',id:i.id,title:i.requested_product})}>Criar tarefa</button></div>):<p className="emptyHint">Nenhum interesse cadastrado.</p>}{cursors.interests&&<button disabled={busy} onClick={()=>void more('interests')}>Carregar mais interesses</button>}</section></div><p className="dataFreshness"><CalendarDays size={14}/> Consulta: {fmt(data.readAt)}</p></>}{editor.element}</section>
}
