import { useState } from 'react'
import { ArrowUpRight, CheckCircle2, RefreshCw } from 'lucide-react'
import { fmt } from './hub'
import type { PendingItem, Source } from './hub'
type Entry={id:string;title:string;reason:string;due:string|null;group:string;open:()=>void;done?:()=>void}
export function PendingCenter({tasks,reminders,events,contacts,nexus,hasMore,loading,error,onView,onSource,onToggle,onReminder,onTask,refresh}:{tasks:any[];reminders:any[];events:any[];contacts:any[];nexus:PendingItem[];hasMore:boolean;loading:boolean;error:string;onView:(v:any)=>void;onSource:(s:Source)=>void;onToggle:(t:any)=>void;onReminder:(r:any)=>void;onTask:(s:Source)=>void;refresh:()=>void}){
 const [filter,setFilter]=useState('all');const now=Date.now(),soon=now+86400000
 const entries:Entry[]=[...tasks.filter(t=>t.status==='pending'&&(t.priority==='high'||t.due_at&&new Date(t.due_at).getTime()<=soon)).map(t=>({id:'t'+t.id,title:t.title,reason:t.due_at&&new Date(t.due_at).getTime()<now?'Tarefa atrasada':t.priority==='high'?'Alta prioridade':'Prazo próximo',due:t.due_at,group:'Tarefas',open:()=>t.origin==='nexus'?onSource({kind:t.source_kind,id:t.source_id}):onView('tasks'),done:()=>onToggle(t)})),...reminders.filter(r=>!r.done&&new Date(r.remind_at).getTime()<=soon).map(r=>({id:'r'+r.id,title:r.title,reason:'Lembrete',due:r.remind_at,group:'Lembretes',open:()=>onView('reminders'),done:()=>onReminder(r)})),...events.filter(e=>new Date(e.starts_at).getTime()>=now&&new Date(e.starts_at).getTime()<=soon).map(e=>({id:'e'+e.id,title:e.title,reason:'Compromisso nas próximas 24h',due:e.starts_at,group:'Agenda',open:()=>onView('calendar')})),...contacts.filter(c=>c.next_contact_at&&new Date(c.next_contact_at).getTime()<=now).map(c=>({id:'c'+c.id,title:c.name,reason:'Retorno pendente',due:c.next_contact_at,group:'Contatos',open:()=>onView('contacts')})),...nexus.map(n=>({id:'n'+n.kind+n.id,title:n.title,reason:n.reason+' · '+n.detail,due:n.due_at,group:'Nexus',open:()=>onSource({kind:n.kind,id:n.id})}))].sort((a,b)=>(a.due?new Date(a.due).getTime():Infinity)-(b.due?new Date(b.due).getTime():Infinity))
 const shown=entries.filter(e=>filter==='all'||e.group===filter)
 return <section className="panel pendingCenter"><div className="panelHead"><div><p className="eyebrow">NENHUMA PONTA SOLTA</p><h2>Central de pendências <span className="countBadge">{entries.length}{hasMore?'+':''}</span></h2></div><button disabled={loading} onClick={refresh}><RefreshCw size={16}/>{loading?'Atualizando...':'Atualizar'}</button></div><p className="muted">Atrasos, alta prioridade e próximos compromissos em um só lugar.</p><div className="filterChips">{['all','Tarefas','Lembretes','Agenda','Contatos','Nexus'].map(v=><button key={v} aria-pressed={filter===v} onClick={()=>setFilter(v)}>{v==='all'?'Tudo':v}</button>)}</div>{error&&<p className="formError" role="status">Nexus: {error} <button onClick={()=>onView('nexus')}>Abrir conexão</button></p>}{shown.length?shown.map(e=><div className="pendingRow" key={e.id}><span className={'pendingDot '+e.group}/><button className="pendingMain" onClick={e.open}><strong>{e.title}</strong><small>{e.reason}</small><time>{fmt(e.due)}</time></button>{e.done?<button aria-label={'Concluir '+e.title} onClick={e.done}><CheckCircle2 size={18}/></button>:<button aria-label={'Abrir '+e.title} onClick={e.open}><ArrowUpRight size={18}/></button>}{e.group==='Nexus'&&<button onClick={()=>{const n=nexus.find(n=>'n'+n.kind+n.id===e.id)!;onTask({kind:n.kind,id:n.id,title:n.title})}}>Criar tarefa</button>}</div>):<div className="calmEmpty"><CheckCircle2 size={30}/><h3>Nenhuma pendência neste filtro</h3><p>Os registros aparecem aqui conforme os prazos e a prioridade.</p></div>}{hasMore&&<p className="muted">Mostrando as 100 primeiras pendências do Nexus. Abra o Nexus para consultar os demais registros.</p>}</section>
}
