import { useEffect, useRef, useState } from 'react'
import { Sparkles } from 'lucide-react'
import { supabase } from './lib/supabase'
import { planAssistant } from './assistantPlan'
import type { Field } from './Editor'
import { useEditor } from './Editor'
import { hub, iso, localInput } from './hub'
const labels:Record<string,string>={title:'Título',priority:'Prioridade',status:'Situação',due_at:'Prazo',remind_at:'Quando lembrar',starts_at:'Início',ends_at:'Término',notes:'Observações',content:'Conteúdo',name:'Nome',next_contact_at:'Próximo retorno',customer:'Cliente',description:'Descrição',amount:'Valor (R$)',sold_at:'Data da venda',done:'Situação'}
const dateFields=new Set(['due_at','remind_at','starts_at','ends_at','next_contact_at'])
export function SmartAssistant({userId,data,onChanged}:{userId:string;data:any;onChanged:()=>void}){
 const [input,setInput]=useState(''),[reply,setReply]=useState(''),[messages,setMessages]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const guard=useRef(false),editor=useEditor()
 useEffect(()=>{let active=true;void supabase.from('assistant_messages').select('*').eq('user_id',userId).order('created_at',{ascending:false}).limit(12).then(({data})=>{if(active)setMessages((data||[]).reverse())});return()=>{active=false}},[userId])
 async function remember(role:string,content:string){const {data,error}=await supabase.from('assistant_messages').insert({user_id:userId,role,content}).select().single();if(data)setMessages(p=>[...p,data].slice(-12));if(error)setError('A ação foi processada, mas o histórico da conversa não pôde ser salvo.')}
 async function prepare(){if(!input.trim()||guard.current)return;guard.current=true;setBusy(true);setError('');const raw=input.trim();try{const plan=planAssistant(raw,data);await remember('user',raw);if(plan.kind!=='action'){setReply(plan.text);await remember('assistant',plan.text);setInput('');return}
 const fields:Field[]=Object.entries(plan.values).map(([name,value])=>({name,label:labels[name]||name,value:dateFields.has(name)?localInput(value as string):name==='done'?(value?'true':'false'):String(value??''),type:dateFields.has(name)?'datetime-local':name==='sold_at'?'date':name==='amount'?'number':['notes','content'].includes(name)?'textarea':'text',required:['title','name','description','amount','remind_at','starts_at','sold_at'].includes(name),min:name==='amount'?0.01:undefined,options:name==='priority'?[['low','Baixa'],['normal','Normal'],['high','Alta']]:name==='status'?[['pending','Pendente'],['done','Concluída']]:name==='done'?[['false','Pendente'],['true','Concluído']]:undefined}))
 editor.open({title:plan.title,description:plan.summary,fields,submitLabel:'Confirmar e executar',save:async values=>{if(!navigator.onLine)throw new Error('Reconecte antes de executar.');const payload:Record<string,unknown>={};for(const [key,value] of Object.entries(values))payload[key]=dateFields.has(key)?iso(value):key==='amount'?Number(value):key==='done'?value==='true':value.trim();if(plan.table==='calendar_events'&&payload.ends_at&&String(payload.ends_at)<String(payload.starts_at))throw new Error('O término deve ser posterior ao início.');if(plan.source?.origin==='nexus')await hub('save_followup',{...plan.source,...payload,expected:plan.source.updated_at});else{if(plan.table==='tasks'&&payload.status==='done')payload.completed_at=new Date().toISOString();const query=plan.id?supabase.from(plan.table).update(payload).eq('id',plan.id).eq('user_id',userId):supabase.from(plan.table).insert({...payload,user_id:userId});const {error}=await query.select('id').single();if(error)throw new Error('Não foi possível salvar. Revise e tente novamente.')}setReply(plan.title+': concluído.');setInput('');await remember('assistant',plan.title+': concluído.');onChanged()}})
 }catch(e){setError(e instanceof Error?e.message:'Não foi possível preparar a ação.')}finally{guard.current=false;setBusy(false)}}
 return <section className="assistantBox"><div className="assistantExamples">{['Quais clientes preciso chamar hoje?','Tarefa ligar para João amanhã às 9','Agendar reunião amanhã às 14h'].map(q=><button key={q} onClick={()=>setInput(q)}>{q}</button>)}</div>{messages.length>0&&<div className="assistantHistory">{messages.slice(-6).map(m=><div key={m.id} className={'assistantMsg '+m.role}><strong>{m.role==='user'?'Você':'Assistente'}</strong><span>{m.content}</span></div>)}</div>}<div className="assistantInput"><Sparkles size={19}/><input aria-label="Pedir ajuda ao assistente" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void prepare()} placeholder="O que você quer organizar?"/><button disabled={busy} onClick={()=>void prepare()}>{busy?'Preparando...':'Preparar ação'}</button></div>{reply&&<p role="status">{reply}</p>}{error&&<p className="formError" role="alert">{error}</p>}<small className="assistantHint">Consultas usam os dados carregados. Alterações sempre passam pela sua revisão.</small>{editor.element}</section>
}
